In [20]:
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score,confusion_matrix, precision_recall_curve
from imblearn.over_sampling import SMOTE
import re

In [21]:
treino = pd.read_csv(r'C:\Users\tomas\Downloads\Desafio 3\Pedidos de reembolso de executivos.csv',sep=';')

In [22]:
treino['receipt_date']=pd.to_datetime(treino['receipt_date'])

In [23]:
treino['day'] = treino['receipt_date'].dt.day
treino['month'] = treino['receipt_date'].dt.month
treino['year'] = treino['receipt_date'].dt.year

In [24]:
treino.head(1)

,bugged_date,receipt_date,employee_id,work_group,state_code,employee,receipt_social_security_number,receipt_description,establishment_name,receipt_value,day,month,year
0,0,2013-03-27,1772,grupo 1,SP,func 1,3.530749e+12,Fuels and lubricants.,AUTO POSTO 314 NORTE LTDA,70,27,3,2013

In [25]:
X = treino.loc[:,('day','month','year','employee_id','receipt_value','bugged_date')]

In [26]:
from sklearn import preprocessing
le = preprocessing.LabelBinarizer()

In [27]:
X = preprocessing.normalize(X)

In [28]:
treino.corr()

,bugged_date,employee_id,receipt_social_security_number,receipt_value,day,month,year
bugged_date,1.000000,0.000010,0.014174,0.007547,-0.245598,-0.234898,0.099155
employee_id,0.000010,1.000000,0.012911,-0.003123,-0.000022,0.004203,0.029037
receipt_social_security_number,0.014174,0.012911,1.000000,-0.011055,-0.010237,-0.022499,-0.012701
receipt_value,0.007547,-0.003123,-0.011055,1.000000,0.017031,0.002337,0.032748
day,-0.245598,-0.000022,-0.010237,0.017031,1.000000,0.050773,-0.039327
month,-0.234898,0.004203,-0.022499,0.002337,0.050773,1.000000,-0.017983
year,0.099155,0.029037,-0.012701,0.032748,-0.039327,-0.017983,1.000000

Isolation Forest

In [29]:
from sklearn.ensemble import IsolationForest

In [30]:
clf=IsolationForest(n_estimators=100, max_samples='auto', contamination=float(.12), \
                        max_features=1.0, bootstrap=True, n_jobs=-1, random_state=42, verbose=0)

In [31]:
clf.fit(X)
pred = clf.predict(X)
treino['anomaly']=pred
outliers=treino.loc[treino['anomaly']== -1]
outlier_index=list(outliers.index)

Contando as anomalias, temos 12% do dataset sendo classificado como fraude / Counting the anomalies, we have 12% of the dataset classified as fraud

In [32]:
treino['anomaly'].value_counts(normalize=True)*100

 1    88.0
-1    12.0
Name: anomaly, dtype: float64

Query das anomalias(-1) com as descrições / Query of anomalies(-1) with discriptions

In [39]:
treino.loc[:,('anomaly','receipt_value','employee_id','receipt_description')]

         anomaly  receipt_value  employee_id    receipt_description
0              1             70         1772  Fuels and lubricants.
1              1            104         1772  Fuels and lubricants.
2              1            100         1772  Fuels and lubricants.
3              1            100         1772  Fuels and lubricants.
4              1             77         1772  Fuels and lubricants.
5              1            131         1772  Fuels and lubricants.
6             -1           2840         1772  Fuels and lubricants.
7              1           2517         1772  Fuels and lubricants.
8              1           2509         1772  Fuels and lubricants.
9              1           2720         1772  Fuels and lubricants.
10             1           2498         1772  Fuels and lubricants.
11            -1           2701         1772  Fuels and lubricants.
12            -1           2724         1772  Fuels and lubricants.
13             1           2110         1772  Fuels and lubricants.
14             1            126         1772  Fuels and lubricants.
15             1           2518         1772  Fuels and lubricants.
16            -1           2799         1772  Fuels and lubricants.
17            -1           3005         1772  Fuels and lubricants.
18             1            150         1772  Fuels and lubricants.
19             1             85         1772  Fuels and lubricants.
20             1             50         1772  Fuels and lubricants.
21             1            116         1772  Fuels and lubricants.
22             1            130         1772  Fuels and lubricants.
23             1            130         1772  Fuels and lubricants.
24             1            115         1772  Fuels and lubricants.
25             1            115         1772  Fuels and lubricants.
26             1             99         1772  Fuels and lubricants.
27             1            100         1772  Fuels and lubricants.
28             1            100         1772  Fuels and lubricants.
29             1            145         1772  Fuels and lubricants.
...          ...            ...          ...                    ...
1048545        1            250         1699  Maintenance of Office
1048546       -1           2876         1699  Maintenance of Office
1048547        1            390         1699  Maintenance of Office
1048548        1             55         1699  Maintenance of Office
1048549        1             59         1699  Maintenance of Office
1048550        1           2400         1699  Maintenance of Office
1048551        1              9         1699  Maintenance of Office
1048552        1             90         1699  Maintenance of Office
1048553        1             27         1699  Maintenance of Office
1048554        1            116         1699  Maintenance of Office
1048555        1             40         1699  Fuels and lubricants.
1048556        1             71         1699  Fuels and lubricants.
1048557        1             76         1699  Fuels and lubricants.
1048558        1           1537         1699  Fuels and lubricants.
1048559        1             23         1699  Fuels and lubricants.
1048560        1             15         1699  Fuels and lubricants.
1048561        1            207         1699  Fuels and lubricants.
1048562        1            100         1699  Fuels and lubricants.
1048563        1             50         1699  Fuels and lubricants.
1048564        1             14         1699  Fuels and lubricants.
1048565        1             14         1699  Fuels and lubricants.
1048566        1             30         1699  Fuels and lubricants.
1048567        1            101         1699  Fuels and lubricants.
1048568        1             40         1699  Fuels and lubricants.
1048569        1             39         1699  Fuels and lubricants.
1048570        1             50         1699  Fuels and lubricants.
1048571        1            100         1699  Fuels and lubricants.
1048572        1             31         1699  Fuels and lubricants.
1048573        1             90         1699  Fuels and lubricants.
1048574        1            170         1699  Fuels and lubricants.

[1048575 rows x 4 columns]